---
abstract: 'The great new Text::Hyphen!'
author:
  - 'Alex Kapranoff, C<< <kappa at cpan.org> >>'
build_requires:
  Test::Deep: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Text-Hyphen
no_index:
  directory:
    - inc
    - t
requires:
  List::Util: 0
  perl: 5.6.0
version: 0.1
